server:
  port: 8090

spring:
  application:
    name: career-path-api-gateway
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedHeaders: "*"
            allowedMethods:
            - GET
            - POST
      routes:
        - id: all-career-path
          uri: lb://ms-career-path-api
          predicates:
          - Path=/api/v1/career-path/
          - Method=GET
        - id: career-path-by-id
          uri: lb://ms-career-path-api
          predicates:
            - Path=/api/v1/career-path/{param}
            - Method=GET
        - id: positions-by-career-path-id
          uri: lb://ms-career-path-positions
          predicates:
            - Path=/api/v1/career-path/{careerPathId}/positions/**
            - Method=GET
      loadbalancer:
        ribbon:
          enable: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka


logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: TRACE
    org.springframework.cloud.gateway.route.RouteDefinitionLocator: INFO